# Configuration simple pour Cancer du sein - Dataset numérique
# Dataset: datasets/Cancer_neuroplast.csv (format optimisé)

# Type de dataset (OBLIGATOIRE)
is_image_dataset: false  # Spécifie que c'est un dataset tabulaire (CSV)

# Identification du dataset pour organisation des modèles
dataset_name: "cancer"

dataset: "datasets/Cancer_neuroplast.csv"
input_cols: 30    # 30 features cancer (après target)
output_cols: 1    # Classification binaire (1=Malignant, 0=Benign)
batch_size: 32
max_epochs: 100   # Plus d'époques pour données réelles
learning_rate: 0.005
debug_mode: false


input_fields: "radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave_points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst"
output_fields: "diagnosis"

# Early stopping pour éviter overfitting
early_stopping: true
patience: 10
train_test_split: 0.8

# Paramètres optimisés d'après v4.1
dropout_rate: 0.0
l2_regularization: 0.0001
momentum: 0.9

# Export des métriques
metrics_export: true
csv_export: true

# Description
name: "cancer_wisconsin_real"
description: "Cancer du sein Wisconsin avec dataset réel (568 échantillons)"

# Format du dataset
data_format: "target_first"  # Format: diagnosis_numeric,feature1,feature2,...,feature30
target_classes: "1=Malignant (212 cas), 0=Benign (356 cas)"
expected_performance: "Objectif 90-95% accuracy" 