# Configuration CANCER optimisée avec dataset synthétique réaliste
# Basée sur les vraies statistiques du Wisconsin Breast Cancer Dataset

dataset: "synthetic_cancer"  # Génération synthétique
input_cols: 30    # 30 features cancer 
output_cols: 1    # Classification binaire M/B
batch_size: 16    # Batch optimal pour convergence
max_epochs: 200   # Suffisant pour convergence complète
learning_rate: 0.0005  # LR prudent pour stabilité

# Early stopping optimisé
early_stopping: true
patience: 40
train_test_split: 0.85

# Hyperparamètres optimisés pour cancer
dropout_rate: 0.05       # Légère régularisation
l2_regularization: 0.00005  # Très légère régularisation
momentum: 0.95

# Gestion du déséquilibre (37% M, 63% B)
class_weights: [1.0, 1.7]

# Configuration pour génération synthétique réaliste
synthetic_config:
  samples: 568
  malignant_ratio: 0.373   # 37.3% comme dans les vraies données
  noise_level: 0.1         # Bruit réaliste
  feature_correlation: 0.8 # Corrélations entre features

# Patterns cancer réalistes (basés sur les vraies données)
cancer_patterns:
  # Features les plus discriminantes (d'après littérature)
  critical_features: [
    "concave_points_worst",  # Index 27 - très discriminant
    "perimeter_worst",       # Index 22
    "concavity_worst",       # Index 26
    "radius_worst",          # Index 20
    "area_worst",            # Index 23
    "compactness_mean",      # Index 5
    "concavity_mean"         # Index 6
  ]
  
  # Seuils typiques pour malignité (valeurs normalisées)
  malignant_thresholds: [
    0.7,  # concave_points_worst > 0.7
    0.6,  # perimeter_worst > 0.6
    0.65, # concavity_worst > 0.65
    0.6,  # radius_worst > 0.6
    0.65, # area_worst > 0.65
    0.55, # compactness_mean > 0.55
    0.5   # concavity_mean > 0.5
  ]

# Métriques prioritaires pour diagnostic médical
priority_metrics: ["accuracy", "precision", "recall", "f1_score", "auc_roc"]

# Instructions optimisées
usage_commands:
  single_test: "./neuroplast-ann --config config/cancer_optimized_synthetic.yml"
  quick_validation: "./neuroplast-ann --config config/cancer_optimized_synthetic.yml --test-all-optimizers"
  full_comparison: "./neuroplast-ann --config config/cancer_optimized_synthetic.yml --test-all"

# Objectifs de performance
performance_targets:
  target_accuracy: 0.92     # 92% objectif réaliste
  minimum_recall: 0.88      # Crucial en médical
  target_f1_score: 0.90     # F1 équilibré

name: "cancer_wisconsin_synthetic_optimized"
description: "Cancer synthétique optimisé - Dataset réaliste basé sur Wisconsin data"

# Export et monitoring
metrics_export: true
csv_export: true
verbose_training: true 