# Configuration simple pour le dataset d'images Chest X-Ray
# Version simplifiée pour tests rapides

# Type de dataset
is_image_dataset: true

# Identification du dataset
dataset_name: "chest_xray_simple"
dataset: "chest_xray_simple"

# Répertoires d'images
image_train_dir: "/Users/fabricevaussenat/SynologyDrive/data-science/chest_xray/chest_xray/train"
image_test_dir: "/Users/fabricevaussenat/SynologyDrive/data-science/chest_xray/chest_xray/test"

# Dimensions d'images (réduites pour tests rapides)
image_width: 8
image_height: 8
image_channels: 1

# Configuration d'entraînement (réduite pour tests rapides)
batch_size: 16
max_epochs: 20
learning_rate: 0.01
debug_mode: false

# Early stopping
early_stopping: true
patience: 5

# Export
metrics_export: true
csv_export: true

# Description
name: "chest_xray_simple_test"
description: "Configuration simple pour tests rapides des radiographies thoraciques"

# Méthodes (version simple)
neuroplast_methods:
  - standard

# Activations (version simple)
activations:
  - relu

# Optimiseurs (version simple)
optimizers:
  - adam

# Métriques
metrics:
  - accuracy
  - f1_score
  - auc_roc 