# Configuration optimisée pour pipeline MLP sur images 32x32 (compatibilité NEUROPLAST-ANN v4.4)

is_image_dataset: true

dataset_name: "chest_xray_pneumonia"

# Répertoires d'images (obligatoires)
image_train_dir: "/Users/fabricevaussenat/SynologyDrive/data-science/chest_xray/chest_xray/train"
image_test_dir: "/Users/fabricevaussenat/SynologyDrive/data-science/chest_xray/chest_xray/test"
image_val_dir: "/Users/fabricevaussenat/SynologyDrive/data-science/chest_xray/chest_xray/val"

# Dimensions d'images (32x32 pour compromis performance/rapidité)
image_width: 32
image_height: 32
image_channels: 1

# Architecture MLP recommandée pour 32x32x1=1024 (Input(1024)→512→256→128→1)
mlp_layer_sizes: [1024, 512, 256, 128, 1]
mlp_activations: ["relu", "relu", "relu", "sigmoid"]

# Paramètres d'entraînement
batch_size: 32
max_epochs: 50
learning_rate: 0.001
momentum: 0.9

dropout_rate: 0.2
l2_regularization: 0.0001

debug_mode: true

# Early stopping
early_stopping: true
patience: 12

# Export des métriques
metrics_export: true
csv_export: true

# Description
name: "chest_xray_pneumonia_mlp32x32"
description: "Classification de pneumonie sur radiographies thoraciques (32x32, MLP dense)"

# Classes attendues
expected_classes: "NORMAL, PNEUMONIA"
expected_performance: "Objectif 65-75% accuracy (MLP 32x32)" 