activations:
- name: NeuroPlast
  optimization_method: bayesian
  optimized_with: nadam
  params:
    alpha_init: 0.20347171131856234
    beta_init: 0.10854643368675157
    plateau_height_init: 0.0848378095399983
    plateau_width_init: 4.449041537359349
    shift_init: 1.1852367231552228
    slope_init: 3.8425238496884755
    trainable: true
- name: ReLU
- name: LeakyReLU
  params:
    negative_slope: 0.01
- name: GELU
- name: Sigmoid
- name: Tanh
- name: ELU
  params:
    alpha: 1.0
- name: Mish
base_dataset: config/cancer.yml
metrics:
- accuracy
- precision
- recall
- f1
- roc_auc
num_runs: 3
optimizers:
- name: adamw
  params:
    lr: 0.001
    weight_decay: 0.01
- name: adam
  params:
    lr: 0.001
- name: sgd
  params:
    lr: 0.01
    momentum: 0.9
- name: rmsprop
  params:
    alpha: 0.99
    eps: 1.0e-08
    lr: 0.001
    momentum: 0.0
- name: lion
  params:
    beta1: 0.9
    beta2: 0.99
    lr: 0.0001
    weight_decay: 0.01
- name: adabelief
  params:
    beta1: 0.9
    beta2: 0.999
    eps: 1.0e-08
    lr: 0.001
    weight_decay: 0.0001
- name: radam
  params:
    beta1: 0.9
    beta2: 0.999
    eps: 1.0e-08
    lr: 0.001
    weight_decay: 0.0001
- name: adamax
  params:
    beta1: 0.9
    beta2: 0.999
    eps: 1.0e-08
    lr: 0.001
    weight_decay: 0.0001
- name: nadam
  params:
    beta1: 0.9
    beta2: 0.999
    eps: 1.0e-08
    lr: 0.001
    weight_decay: 0.0001
training:
  batch_size: 32
  max_epochs: 100
  patience: 15
  verbose: true
visualizations:
  activation_params: true
  bar_charts: true
  best_combinations: 10
  comparison_heatmap: true
  feature_importance: true
  heatmap: true
