# Configuration pour dataset Diabète - Analyse automatique des champs
# NEUROPLAST-ANN v4.3 avec dataset_analyzer intégré

# Type de dataset (OBLIGATOIRE pour l'analyseur)
is_image_dataset: false  # Dataset tabulaire avec analyse automatique

# Identification du dataset
dataset_name: "diabetes"
dataset: "datasets/diabetes.csv"

# Définition des champs (NOUVEAU SYSTÈME)
# Liste des champs d'entrée (features) pour le diabète - CORRIGÉ AVEC LES VRAIS NOMS
input_fields: "Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age"

# Liste des champs de sortie (targets) - CORRIGÉ AVEC LE VRAI NOM
output_fields: "Outcome"

# Le système détectera automatiquement :
# - Type numérique vs catégorique pour chaque champ
# - Appliquera la normalisation min-max pour les champs numériques
# - Appliquera la binarisation 0/1 pour les champs catégoriques

# Dimensions (optionnelles - détectées automatiquement)
input_cols: 8    # Sera validé par l'analyseur
output_cols: 1   # Classification binaire diabète

# Configuration d'entraînement
batch_size: 32
max_epochs: 120
learning_rate: 0.002
debug_mode: false

# Early stopping optimisé
early_stopping: true
patience: 12
train_test_split: 0.75

# Régularisation
dropout_rate: 0.15
l2_regularization: 0.001

# Configuration avancée pour l'analyseur
auto_normalize: true      # Normalisation automatique des champs numériques
auto_categorize: true     # Binarisation automatique des champs catégoriques
field_detection: "auto"   # Détection automatique des types de champs

# Optimisation pour dataset diabetes
optimized_parameters: false  # Configuration manuelle pour ce test

# Méthodes neuroplast à tester
neuroplast_methods:
  - name: "adaptive"
  - name: "advanced"
  - name: "standard"

# Optimiseurs à tester
optimizers:
  - name: "adam"
  - name: "adamw"
  - name: "sgd"

# Activations à tester
activations:
  - name: "neuroplast"
  - name: "relu"
  - name: "sigmoid"

# Métriques à calculer
metrics:
  - name: "accuracy"
  - name: "precision"
  - name: "recall"
  - name: "f1_score"
  - name: "auc_roc" 