# Configuration DYNAMIQUE ADAPTATIVE - Itération 7
# ================================================
# Générée automatiquement par l'optimiseur adaptatif

# Paramètres adaptatifs optimisés
max_epochs: 100          # Époques par cycle d'adaptation
early_stopping: true     # Early stopping intelligent
patience: 25             # Patience adaptative
batch_size: 8           # Batch size adaptatif
learning_rate: 0.001000     # Learning rate dynamique

# Régularisation adaptative
dropout_rate: 0.100       # Dropout adaptatif
l2_regularization: 0.000100  # L2 adaptatif
momentum: 0.900           # Momentum adaptatif

# Gestion des classes adaptative
class_weights: [1.0, 1.5]  # Ratio adaptatif

# Méthodes neuroplast optimisées
neuroplast_methods:
  - neuroplast           # Méthode spécialisée
  - adaptive             # Méthode adaptative
  - standard             # Standard pour comparaison

# Optimiseurs adaptatifs
optimizers:
  - adamw               # AdamW optimal
  - adam                # Adam backup

# Activations optimisées
activations:
  - neuroplast          # Activation spécialisée
  - gelu                # GELU performant
  - relu                # ReLU standard

# Métriques complètes
metrics:
  - accuracy
  - f1_score
  - precision
  - recall

# Export et monitoring
metrics_export: true
csv_export: true

name: "dynamic_adaptive_iter_7"
description: "Configuration adaptative dynamique - Itération 7"

# Historique des adaptations
adaptation_history: |
  🔄 CYCLE D'ADAPTATION 7:
  
  📊 PARAMÈTRES ACTUELS:
  - Learning Rate: 0.001000 (Stratégie: 0)
  - Momentum: 0.900 (Stratégie: 0)
  - Dropout: 0.100 (Stratégie: 0)
  - Batch Size: 8 (Stratégie: 0)
  - Class Weight Ratio: 1.5
  
  🎯 MÉTRIQUES CIBLES:
  - Accuracy: >90%
  - F1-Score: >90%
  - Precision: >85%
  - Recall: >85%
  
  📈 COMPTEURS:
  - Stagnation: 0
  - Amélioration: 4
  - Oscillation: 0
