# Configuration pour dataset Maladie Cardiaque - Analyse automatique des champs
# NEUROPLAST-ANN v4.3 avec dataset_analyzer intégré

# Type de dataset (OBLIGATOIRE pour l'analyseur)
is_image_dataset: false  # Dataset tabulaire avec analyse automatique

# Identification du dataset
dataset_name: "heart_disease"
dataset: "datasets/heart_disease.csv"

# Définition des champs (NOUVEAU SYSTÈME)
# Liste des champs d'entrée (features) pour les maladies cardiaques - CORRIGÉ AVEC LES VRAIS NOMS
input_fields: "HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income"

# Liste des champs de sortie (targets) - CORRIGÉ AVEC LE VRAI NOM
output_fields: "HeartDiseaseorAttack"

# Le système détectera automatiquement :
# - Type numérique vs catégorique pour chaque champ
# - Appliquera la normalisation min-max pour les champs numériques (BMI, GenHlth, MentHlth, PhysHlth, Age)
# - Appliquera la binarisation 0/1 pour les champs catégoriques (HighBP, HighChol, CholCheck, Smoker, Stroke, Diabetes, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, DiffWalk, Sex, Education, Income)

# Dimensions (optionnelles - détectées automatiquement)
input_cols: 21   # Sera validé par l'analyseur - CORRIGÉ (21 features au lieu de 13)
output_cols: 1   # Classification binaire maladie cardiaque

# Configuration d'entraînement
batch_size: 16
max_epochs: 100
learning_rate: 0.001
debug_mode: false

# Early stopping optimisé
early_stopping: true
patience: 10
train_test_split: 0.8

# Régularisation
dropout_rate: 0.2
l2_regularization: 0.0008

# Configuration avancée pour l'analyseur
auto_normalize: true      # Normalisation automatique des champs numériques
auto_categorize: true     # Binarisation automatique des champs catégoriques
field_detection: "auto"   # Détection automatique des types de champs

# Optimisation pour dataset heart disease
optimized_parameters: false  # Configuration manuelle pour ce test

# Méthodes neuroplast à tester
neuroplast_methods:
  - name: "bayesian"
  - name: "adaptive"
  - name: "advanced"

# Optimiseurs à tester
optimizers:
  - name: "adamw"
  - name: "radam"
  - name: "adam"

# Activations à tester
activations:
  - name: "neuroplast"
  - name: "gelu"
  - name: "swish"

# Métriques à calculer
metrics:
  - name: "accuracy"
  - name: "precision"
  - name: "recall"
  - name: "f1_score"
  - name: "auc_roc" 