# Configuration EXHAUSTIVE pour test de TOUTES les combinaisons
# ===========================================================

# Paramètres d'entraînement optimisés pour >95% accuracy
max_epochs: 150          # Époques augmentées pour meilleure convergence
early_stopping: true     # Early stopping activé
patience: 30             # Patience élevée
batch_size: 4            # Batch size optimal
learning_rate: 0.003     # Learning rate augmenté

# Optimisation adaptative temps réel - DÉSACTIVÉ POUR TEST EXHAUSTIF
optimized_parameters: false  # Désactiver pour test exhaustif complet

# Régularisation
dropout_rate: 0.0        # Pas de dropout
l2_regularization: 0.0001 # L2 légère

# Momentum
momentum: 0.9            # Momentum standard

# Gestion des classes
class_weights: [1.0, 1.5]  # Pondération optimisée

# TOUTES les méthodes neuroplast (7 méthodes)
neuroplast_methods:
  - standard
  - adaptive
  - advanced
  - bayesian
  - progressive
  - swarm
  - propagation

# TOUS les optimiseurs (9 optimiseurs)
optimizers:
  - adamw
  - adam
  - sgd
  - rmsprop
  - lion
  - adabelief
  - radam
  - adamax
  - nadam

# TOUTES les activations (9 activations)
activations:
  - neuroplast
  - relu
  - leaky_relu
  - gelu
  - sigmoid
  - elu
  - mish
  - swish
  - prelu

# Métriques complètes
metrics:
  - accuracy
  - precision
  - recall
  - f1_score
  - auc_roc 