# Configuration de test simple
batch_size: 16
max_epochs: 10
learning_rate: 0.001
early_stopping: true
patience: 5

# Méthodes de neuroplasticité
neuroplast_methods:
  - name: "standard"

# Fonctions d'activation
activations:
  - name: "relu"

# Optimiseurs
optimizers:
  - name: "adam"

# Métriques
metrics:
  - name: "accuracy" 