# Configuration FINALE OPTIMISÉE pour 90%+ d'accuracy
# ===================================================
# Basée sur test_convergence.yml mais avec paramètres ultra-optimisés

# Paramètres d'entraînement ultra-optimisés pour 90%+
max_epochs: 300          # Plus d'époques pour convergence complète
early_stopping: true     # Early stopping intelligent
patience: 80             # Patience très élevée pour adaptation fine
batch_size: 2            # Batch size ultra-petit pour précision maximale
learning_rate: 0.00005   # Learning rate ultra-bas pour fine-tuning

# Régularisation ultra-optimisée
dropout_rate: 0.0        # Aucun dropout pour expressivité maximale
l2_regularization: 0.0   # Aucune L2 pour expressivité maximale
momentum: 0.95           # Momentum très élevé pour stabilité

# Gestion des classes ultra-optimisée pour 90%+
class_weights: [1.0, 4.0]  # Ratio très agressif pour classes déséquilibrées

# Méthodes neuroplast spécialisées
neuroplast_methods:
  - neuroplast           # Méthode spécialisée prioritaire
  - adaptive             # Méthode adaptative

# Optimiseurs haute performance
optimizers:
  - adamw               # AdamW optimal en priorité
  - adam                # Adam comme backup

# Activations ultra-optimisées
activations:
  - neuroplast          # Activation spécialisée prioritaire
  - gelu                # GELU performant
  - swish               # Swish pour diversité

# Métriques complètes
metrics:
  - accuracy
  - f1_score
  - precision
  - recall

name: "test_convergence_90plus_final"
description: "Configuration finale optimisée pour 90%+ accuracy"

# Instructions d'optimisation
optimization_notes: |
  🎯 CONFIGURATION FINALE POUR 90%+ ACCURACY:
  
  ✅ OPTIMISATIONS ULTRA-AGRESSIVES:
  - Learning rate divisé par 20 (0.00005 vs 0.001)
  - Batch size divisé par 8 (2 vs 16)
  - Momentum augmenté (0.95 vs 0.9)
  - Class weights quadruplés (4.0 vs 1.0)
  - Patience quadruplée (80 vs 20)
  - Époques triplées (300 vs 100)
  - Aucune régularisation (dropout=0, L2=0)
  
  📈 STRATÉGIE:
  - Fine-tuning ultra-précis avec learning rate minimal
  - Gradients ultra-précis avec batch size minimal
  - Stabilité maximale avec momentum élevé
  - Compensation agressive du déséquilibre des classes
  - Convergence complète avec patience élevée
  
  🎯 OBJECTIF: 90-95% accuracy
  🚀 UTILISATION: ./neuroplast-ann --config config/test_convergence_90plus_final.yml --test-all 