# Configuration ULTRA-OPTIMISÉE STATIQUE pour 90%+ d'accuracy
# ============================================================
# Paramètres ultra-agressifs pour dépasser 90% (mode statique)

# Paramètres d'entraînement ULTRA-OPTIMISÉS pour 90%+
max_epochs: 500          # Beaucoup plus d'époques pour convergence complète
early_stopping: true     # Early stopping pour éviter overfitting
patience: 100            # Patience très élevée pour convergence ultra-fine
batch_size: 1            # Batch size minimal pour gradients ultra-précis
learning_rate: 0.00001   # Learning rate ultra-ultra-bas pour fine-tuning extrême

# Optimisation adaptative temps réel
optimized_parameters: false  # Configuration statique (pas d'optimiseur temps réel)

# Régularisation ultra-optimisée
dropout_rate: 0.0        # Aucun dropout pour expressivité maximale
l2_regularization: 0.0   # Aucune L2 pour expressivité maximale

# Momentum ultra-optimal
momentum: 0.99           # Momentum très élevé pour stabilité maximale

# Gestion des classes ULTRA-optimisée pour 90%+
class_weights: [1.0, 5.0]  # Pondération très agressive pour classes déséquilibrées

# Méthodes neuroplast ultra-optimisées (focus sur les plus performantes)
neuroplast_methods:
  - neuroplast           # Méthode spécialisée la plus performante UNIQUEMENT
  - adaptive             # Méthode adaptative

# Optimiseurs ultra-optimisés (focus sur le meilleur)
optimizers:
  - adamw               # AdamW UNIQUEMENT - le meilleur selon nos tests

# Activations ultra-optimisées (focus sur les meilleures)
activations:
  - neuroplast          # Activation spécialisée UNIQUEMENT
  - gelu                # GELU comme backup

# Métriques complètes
metrics:
  - accuracy
  - f1_score
  - precision
  - recall

# Commentaires d'optimisation ultra-agressive
# ============================================
# CHANGEMENTS POUR 90%+:
# - max_epochs: 200 -> 500 (+150% époques)
# - batch_size: 4 -> 1 (-75% pour précision maximale)
# - learning_rate: 0.0001 -> 0.00001 (-90% pour fine-tuning extrême)
# - patience: 50 -> 100 (+100% patience)
# - momentum: 0.9 -> 0.99 (+10% stabilité)
# - class_weights: [1.0, 2.0] -> [1.0, 5.0] (+150% compensation)
# - optimized_parameters: false (mode statique)
# - Réduction des options pour focus sur les meilleures
# 
# STRATÉGIE ULTRA-AGRESSIVE STATIQUE:
# 1. Fine-tuning extrême avec LR minimal
# 2. Gradients ultra-précis avec batch=1
# 3. Convergence ultra-stable avec momentum=0.99
# 4. Compensation maximale du déséquilibre (5:1)
# 5. Patience maximale pour convergence complète
# 6. Focus uniquement sur les méthodes les plus performantes
# 7. CONFIGURATION STATIQUE (pas d'adaptation automatique) 