# Configuration de test pour Early Stopping et Époques Configurables
# ====================================================================

# Paramètres de base
batch_size: 64
learning_rate: 0.002

# Configuration des époques et early stopping
max_epochs: 75           # Moins d'époques pour test rapide
early_stopping: true     # Early stopping activé
patience: 15             # Patience de 15 époques

# Méthodes neuroplast
neuroplast_methods:
  - standard
  - adaptive

# Optimiseurs
optimizers:
  - adamw
  - adam

# Fonctions d'activation
activations:
  - neuroplast
  - relu

# Métriques
metrics:
  - accuracy
  - f1_score 