# Configuration EXHAUSTIVE COMPLÈTE - 567 combinaisons
# ====================================================
# Test de TOUTES les combinaisons possibles avec barres de progression

# Paramètres d'entraînement optimisés pour tests exhaustifs
max_epochs: 50           # Époques raisonnables pour tests rapides
early_stopping: true     # Early stopping activé
patience: 15             # Patience modérée
batch_size: 32           # Batch size standard
learning_rate: 0.001     # Learning rate standard

# Mode statique pour test exhaustif
optimized_parameters: false  # MODE STATIQUE pour test exhaustif complet

# Régularisation
dropout_rate: 0.1        # Dropout léger
l2_regularization: 0.0001 # L2 légère

# Momentum
momentum: 0.9            # Momentum standard

# Gestion des classes
class_weights: [1.0, 1.0]  # Pas de pondération pour tests génériques

# TOUTES les méthodes neuroplast (7 méthodes)
neuroplast_methods:
  - standard
  - adaptive
  - advanced
  - bayesian
  - progressive
  - swarm
  - propagation

# TOUS les optimiseurs (9 optimiseurs)
optimizers:
  - adamw
  - adam
  - sgd
  - rmsprop
  - lion
  - adabelief
  - radam
  - adamax
  - nadam

# TOUTES les activations (9 activations)
activations:
  - neuroplast
  - relu
  - leaky_relu
  - gelu
  - sigmoid
  - tanh
  - elu
  - mish
  - swish

# Métriques complètes
metrics:
  - accuracy
  - f1_score
  - precision
  - recall

# Total: 7 × 9 × 9 = 567 combinaisons
# Avec 3 essais par combinaison = 1701 entraînements 